services:
  source:
    image: debian:bookworm
    container_name: source
    hostname: source
    networks:
      inquisitor:
        ipv4_address: 1.1.1.10
    sysctls:
      - net.ipv4.conf.all.arp_accept=1
      - net.ipv4.conf.eth0.arp_accept=1
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.eth0.accept_redirects=0
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "apt-get update && apt-get install -y iproute2 iputils-ping net-tools tcpdump && tail -f /dev/null"

  target:
    image: debian:bookworm
    container_name: target
    hostname: target
    networks:
      inquisitor:
          ipv4_address: 1.1.1.20
    sysctls:
      - net.ipv4.conf.all.arp_accept=1
      - net.ipv4.conf.eth0.arp_accept=1
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.eth0.accept_redirects=0
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "apt-get update && apt-get install -y iproute2 iputils-ping net-tools tcpdump && tail -f /dev/null"

  attacker:
    build:
      context: ../
      dockerfile: ./_docker/Dockerfile
    container_name: attacker
    hostname: attacker
    networks:
      inquisitor:
          ipv4_address: 1.1.1.42
    sysctls:
      - net.ipv4.conf.all.arp_accept=1
      - net.ipv4.conf.eth0.arp_accept=1
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.send_redirects=0
      - net.ipv4.conf.eth0.send_redirects=0
    cap_add:
      - NET_ADMIN
    volumes:
      - ..:/inquisitor

networks:
  inquisitor:
    driver: bridge
    ipam:
      config:
        - subnet: 1.1.1.0/24
